### PR TITLE
Fix to delete user when unregister for notifications failed

### LINKED ISSUE #3105: bruteforce falsely throttling login
### Steps to reproduce

sometimes bruteforce detection is kickin in.

grafik

might be related to ssl certificate, at least i sometimes observed this in combination.
But so far I could never reproduce it on purpose.
Assumption: maybe it only occurs under certain circumstances when you restart the app and in the meantime the server (e.g. with docker) has been set up anew.

### Expected behaviour

No use of bruteforce unless there is a legitimate reason to do so.

### Actual behaviour

bruteforce sometimes klicks in

### Nextcloud Talk app version

16.1.0 & higher, probably also lower

### LINKED ISSUE #3115: Failed login credentials keep being retried by the app
### Steps to reproduce

1. Open Nextcloud Talk
2. Do several failed login attempts
3. Login with the correct user login details
4. Use the app and re-open it through normal usage or push notifications

### Expected behaviour

The app should work just fine and you should be able to chat and make calls.

### Actual behaviour

The app stops working after some usage (depends on formerly failed login attempts) because of it trying to login with (all) the wrong credentials in the background.
The colleague who has to deal with the problem also tried reinstalling the app on his Xiaomi smartphone but the error messages in the nginx error.log regarding him trying to log in still appears.
Also the oc_bruteforce_attempts table shows his IP trying to login with the wrong credentials again.

### Device brand and model

Xiaomi Mi 11T

### Android version

13TP1A.220624.014

### Nextcloud Talk app version

17.0.0

### Nextcloud server version

27.0.0.8

### Talk version

17.0.0

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Android logs

_No response_

### Server log

_No response_

### Additional information

Output of the oc_bruteforce_attempts table which was cleared right before the app reinstallation:
`mysql> select * from oc_bruteforce_attempts;
+------+--------+------------+----------------+-------------------+-------------------+
| id   | action | occurred   | ip             | subnet            | metadata          |
+------+--------+------------+----------------+-------------------+-------------------+
| 1744 | login  | 1687465247 | XX.XXX.XXX.XXX | XX.XXX.XXX.XXX/32 | {"user":"Tomtom"} |
| 1745 | login  | 1687465248 | XX.XXX.XXX.XXX | XX.XXX.XXX.XXX/32 | {"user":"TomTom"} |
| 1746 | login  | 1687465396 | XX.XXX.XXX.XXX | XX.XXX.XXX.XXX/32 | {"user":"Tomtom"} |
| 1747 | login  | 1687465397 | XX.XXX.XXX.XXX | XX.XXX.XXX.XXX/32 | {"user":"TomTom"} |
| 1748 | login  | 1687465439 | XX.XXX.XXX.XXX | XX.XXX.XXX.XXX/32 | {"user":"Tomtom"} |
| 1749 | login  | 1687465443 | XX.XXX.XXX.XXX | XX.XXX.XXX.XXX/32 | {"user":"TomTom"} |
+------+--------+------------+----------------+-------------------+-------------------+`

nginx error.log:

`2023/06/22 19:37:25 [error] 1071566#1071566: *4113433 FastCGI sent in stderr: "PHP message: {"reqId":"lsW0oIQ24x167pHvk0Wv","level":2,"time":"2023-06-22T19:37:25+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'TomTom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 19:47:13 [error] 1071566#1071566: *4113552 FastCGI sent in stderr: "PHP message: {"reqId":"8xwzyuUD7LsVedAWN9uW","level":2,"time":"2023-06-22T19:47:13+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'Tomtom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 19:47:26 [error] 1071566#1071566: *4113552 FastCGI sent in stderr: "PHP message: {"reqId":"TgXjFgppEExz4EgonQjO","level":2,"time":"2023-06-22T19:47:26+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'TomTom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 22:20:48 [error] 1071567#1071567: *4114283 FastCGI sent in stderr: "PHP message: {"reqId":"P3cKZqARNRThWcKIXlry","level":2,"time":"2023-06-22T22:20:47+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'Tomtom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 22:20:48 [error] 1071567#1071567: *4114283 FastCGI sent in stderr: "PHP message: {"reqId":"cBczfmIgBBoXQwwPiZbX","level":2,"time":"2023-06-22T22:20:48+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'TomTom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 22:23:16 [error] 1071567#1071567: *4114409 FastCGI sent in stderr: "PHP message: {"reqId":"xZll9f192XcJsXXEzJfL","level":2,"time":"2023-06-22T22:23:16+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'Tomtom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 22:23:17 [error] 1071567#1071567: *4114409 FastCGI sent in stderr: "PHP message: {"reqId":"4PCHHeyeGMPgOLi2dm46","level":2,"time":"2023-06-22T22:23:17+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'TomTom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 22:23:59 [error] 1071567#1071567: *4114490 FastCGI sent in stderr: "PHP message: {"reqId":"Bvni34ZwGASURHKU65PF","level":2,"time":"2023-06-22T22:23:59+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'Tomtom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"
2023/06/22 22:24:03 [error] 1071567#1071567: *4114490 FastCGI sent in stderr: "PHP message: {"reqId":"U2pZVhSaZhhMo7r6zrpr","level":2,"time":"2023-06-22T22:24:03+02:00","remoteAddr":"XX.XXX.XXX.XXX","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'TomTom' (Remote IP: 'XX.XXX.XXX.XXX')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v17.0.0","version":"27.0.0.8","data":{"app":"core"}}" while reading response header from upstream, client: XX.XXX.XXX.XXX, server: cloud.example.com, request: "DELETE /ocs/v2.php/apps/notifications/api/v2/push HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "cloud.example.com"`

Signaling Server version: d4eafc851a97e674eeb10610eaeefa1c1d4276b5

### LINKED ISSUE #3243: Login-Error “The account is scheduled for deletion, and cannot be changed”
### Steps to reproduce

Installed Talk on Android
Added path to Nextcloud-Instance

### Expected behaviour

Login-Process

### Actual behaviour

Error: The account is scheduled for deletion, and cannot be changed

### Device brand and model

Samsung Galaxy S23 (SM-911B/DS)

### Android version

13

### Nextcloud Talk app version

17.0.2

### Nextcloud server version

26.0.4.2

### Talk version

16.0.5

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Android logs

_No response_

### Server log

_No response_

### Additional information
Web-Login with the same username is working. The account is not scheduled for deletion.
Some other users do have the same problem: [https://help.nextcloud.com/t/nc-talk-das-konto-wird-geloscht/165766](https://help.nextcloud.com/t/nc-talk-das-konto-wird-geloscht/165766)

### PR DESCRIPTION
**Pull request by mahibi**
it's not yet tested, but from my pov this should...
fix #3243
fix #3105

Not sure for which cases unregister for notifications might fail, maybe @nickvergessen knows best.
Further improvements for user deletions will come with https://github.com/nextcloud/talk-android/pull/3436

### 🚧 TODO

- [ ] do some manual debugging/testing

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java [hunk 1]
```diff
@@ -129,6 +129,7 @@ public void onNext(@io.reactivex.annotations.NonNull GenericOverall genericOvera
                         @Override
                         public void onError(@io.reactivex.annotations.NonNull Throwable e) {
                             Log.e(TAG, "error while trying to unregister Device For Notifications", e);
+                            initiateUserDeletion(user);
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java:132]: especially this missing deletion command caused bugs..

**Review by AndyScherzinger — APPROVED** [review]
Lgtm code wise 👍

**Comment by nickvergessen** [comment]
> Not sure for which cases unregister for notifications might fail

Nextcloud Server? Invalid auth because the token was removed, ...
Push proxy? Invalid user key because it was updated/changed somehow (reinstall of a setup etc. Incomplete backup restore, ...)
