### PR TITLE
hide "unread mention" bubble in search mode

### LINKED ISSUE #2464: hide "unread mention" bubble in search mode
### Steps to reproduce

prepare:
- join multiple conversations just to fill the conversation list (e.g. "test1" - "test12"). All the conversations on display should be marked as favourite so scrolling is necessary to see all of them, otherwise create more conversations or choose device with smaller screen.
  - mark these conversations as favourite via: long press on conversation - "Add to favourites". This needs to be done to assure conversations with mentions are not moved to the top of the list.
- be mentioned by another person in another conversation (e.g. "test13"). Do NOT mark this conversation as favourite, so it's listed below the favourite conversations.
- with this being done, there should be a "unread mentions" bubble when scrolling to the top. Clicking this bubble will scroll to the conversation with the unread mention.

reproduce bug:
- while the "unread mentions" bubble is shown, tap into the search field to search for conversations/messages.

## Expected behaviour
bubble is hidden as long as the search is active. When leaving the search mode, the bubble should be shown again.

## Actual behaviour
bubble is still shown.

grafik

### PR DESCRIPTION
**Pull request by sowjanyakch**
Resolves #2464

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Screenshot 2023-10-30 at 20 47 22|Screenshot 2023-10-30 at 20 44 45

This pull request hides the “unread mention” bubble when the search is activated https://github.com/nextcloud/talk-android/issues/2464

This pull request uses the BehaviorSubject to monitor the activation state of the search mode. BehaviorSubject emits true (boolean value) when search mode is active and false (boolean value) when search mode is inactive. 
UI elements should subscribe to the BehaviorSubject and show or hide the “unread mention” bubble based on search mode activation state. If the BehaviorSubject emits true, the UI hides “unread mention” bubble, whereas when the BehaviorSubject emits false, the ”unread mention” bubble is shown.  

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

**Comment by mahibi** [comment]
Hi @sowjanyakch 

thanks for your PR, it works as expected :+1: 

just one minor remark:
you could format the code (Strg + Alt + L) so it should fit the codestyle.
I guess after this it's already ready to be merged.

File: app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt [hunk 1]
```diff
@@ -869,31 +877,39 @@ class ConversationsListActivity :
...
-        try {
-            val lastVisibleItem = layoutManager!!.findLastCompletelyVisibleItemPosition()
-            for (flexItem in conversationItems) {
-                val conversation: Conversation = (flexItem as ConversationItem).model
-                val position = adapter!!.getGlobalPositionOf(flexItem)
-                if (hasUnreadItems(conversation) && position > lastVisibleItem) {
-                    nextUnreadConversationScrollPosition = position
-                    if (!binding?.newMentionPopupBubble?.isShown!!) {
-                        binding?.newMentionPopupBubble?.show()
+        searchBehaviorSubject.subscribe { value ->
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt:883]: lint complains about "The result of subscribe is not used". 
I guess for this case it's okay to add
@SuppressLint("CheckResult")

**Comment by mahibi** [comment]
Thank you @sowjanyakch , well done :+1:
