### PR TITLE
Fixing federated acceptance messages

### LINKED ISSUE #4072: System messages related to federated invites are rendered as user messages
### Steps to reproduce

image

vs.

image

### Device brand and model

Simulator Pixel 8

### Android version

15

### Nextcloud Talk app version

master

### PR DESCRIPTION
**Pull request by rapterjet2004**
- fixes #4072 

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
Screenshot 2024-08-15 at 10 39 03 AM | Screenshot 2024-08-15 at 10 37 06 AM

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 1]
```diff
@@ -3371,7 +3369,7 @@ class ChatActivity :
             CONTENT_TYPE_VOICE_MESSAGE -> message.isVoiceMessage
             CONTENT_TYPE_POLL -> message.isPoll()
             CONTENT_TYPE_LINK_PREVIEW -> message.isLinkPreview()
-            CONTENT_TYPE_SYSTEM_MESSAGE -> !TextUtils.isEmpty(message.systemMessage)
+            CONTENT_TYPE_SYSTEM_MESSAGE -> message.messageType == "system"
```
Comment (SystemKeeper) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:3372]: Any idea why the previous check did not work? Because `systemMessage` should not be empty in this case?
image

Comment (rapterjet2004) [reply app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt]: Ahh, I see, seems that the federated_user_added and federated_user_removed weren't added to the system message type enum. Should be fixed properly now.

**Review by SystemKeeper — APPROVED** [review]
Seems to work fine now 👍 
But please change the commit message to a more descriptive commit message before merging 😉
