### PR TITLE
🧮 Markdown Tables

### LINKED ISSUE #4815: Markdown tables do not render in Android App (or ios app)
### Steps to reproduce

1. Write a markdown table in a browser message composer in a talk chat
2. Send the message
3. Note the table does not render in the Android or ios apps
4. Note that the table _does_ render properly in the browser 

### Expected behaviour

Markdown tables show as tables in Android Talk app

### Actual behaviour

The unrendered text of the markdown table shows instead of the clean rendered table.

### Device brand and model

Pixel 5a

### Android version

14

### Nextcloud Talk app version

21.0.0

### Nextcloud server version

30.0.6

### Talk version

_No response_

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Android logs

_No response_

### Server log

```bash

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rapterjet2004**
- fixes #4815 

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
 | 

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt [hunk 1]
```diff
@@ -103,10 +104,26 @@ class IncomingTextMessageViewHolder(itemView: View, payload: Any) :
...
+            )
+
+            if (spansFromString.isNotEmpty()) {
+                binding.bubble.layoutParams.apply {
+                    width = FlexboxLayout.LayoutParams.MATCH_PARENT
+                }
+                binding.messageText.layoutParams.apply {
+                    width = FlexboxLayout.LayoutParams.MATCH_PARENT
+                }
+            }
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt:121]: this will cause that the width is not reset for other bubbles. So sending some random short text after sending a table, the width is still the one of the table.

Adding an else which sets the width to WRAP_CONTENT should solve it.

File: app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt [hunk 2]
```diff
@@ -116,10 +116,26 @@ class OutcomingTextMessageViewHolder(itemView: View) :
...
+            )
+
+            if (spansFromString.isNotEmpty()) {
+                binding.bubble.layoutParams.apply {
+                    width = FlexboxLayout.LayoutParams.MATCH_PARENT
+                }
+                binding.messageText.layoutParams.apply {
+                    width = FlexboxLayout.LayoutParams.MATCH_PARENT
+                }
+            }
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt:133]: see comment for Incoming..ViewHolder

**Review by mahibi — CHANGES_REQUESTED** [review]
