### PR TITLE
fix file name of voice recording

### LINKED ISSUE #1564: Check file name of audio recordings
- [ ] Filter out special chars which are not allowed on the filesystem, e.g. `/`, `\` and `:` and replace them with a space
- [ ] Replace multiple spaces with 1
- [ ] Make sure the full filename is not exceeding 250 chars, so trim the name to 246 chars before ammending the filesuffix

Server ref https://github.com/nextcloud/spreed/issues/6174

### PR DESCRIPTION
**Pull request by sowjanyakch**
Fix #1564

- [x] Filter out special chars which are not allowed on the filesystem, e.g. `/`, `\` and `:` and replace them with a space
- [x] Replace multiple spaces with 1 space
- [x] Make sure the full filename is not exceeding 150 chars, so trim the name to 146 chars before ammending the filesuffix

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt [hunk 1]
```diff
@@ -27,6 +27,7 @@ object FileUtils {
     private val TAG = FileUtils::class.java.simpleName
     private const val RADIX: Int = 16
     private const val MD5_LENGTH: Int = 32
+    const val FILE_MAX_LENGTH = 146
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt:30]: the max length is set to 146 instead 150 because of the suffix ".mp3". This is not obvious in the FileUtils class and may lead to confusion. So i suggest to define the max length inside MediaRecorderManager and call it "VOICE_MESSAGE_PREFIX_MAX_LENGTH"

**Review by mahibi — APPROVED** [review]
