### PR TITLE
fix missing file icons in chat

### LINKED ISSUE #2691: File icons in chat are missing
### Steps to reproduce

1.) Open Talk
2.) Send file attachment
3.) Icon for file is missing, so it's not clickable to open it

Workaround: Shared-Items  via menu.

### Expected behaviour

Open the attachment

### Actual behaviour

Attachment only displayed as text

### Device brand and model

diverse

### Android version

na

### Nextcloud Talk app version

15.1.0

### Nextcloud server version

25.0.2

### Talk version

15.0.2

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Android logs

_No response_

### Server log

_No response_

### Additional information

In android app version 15.0.3 the attachments worked

### PR DESCRIPTION
**Pull request by mahibi**
fix #2691

bug was introduced with fresco->coil migration

🏚️ Before | 🏡 After
---|---
grafik | grafik

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [x] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt [hunk 1]
```diff
@@ -228,6 +214,35 @@ abstract class PreviewMessageViewHolder(itemView: View?, payload: Any?) :
             true,
             viewThemeUtils!!
         )
+
+        // super.onBind is at this position, because:
+        // - it needs to be called after "placeholder" is set (otherwise placeholders are initially not loaded)
+        // - it needs to be before the show/hide logic is set (because super methods also have logic for this, which
+        // needs to be overwritten again)
+        super.onBind(message)
```
Comment (AlvaroBrey) [inline app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt:222]: This feels like a bit too finicky of a solution, but I guess it's fine in the interest of fixing the bug ASAP. At a minimum I would separate the logic to get the placeholder into its own method and call only that before `super.onBind` instead of all the rest.

I don't understand how this worked before with Fresco :\ It seems like the same problem would happen

**Review by AlvaroBrey — APPROVED** [review]

File: app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt (hunk 1 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt:222]: yes it's not a clean solution but it's gonna be a hotfix asap.
will extract the placeholder logic.

the "placeholder" solution was introduced when coil was introduced. but now i think of an easier solution. will have another look in the evening..

Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt]: for now i moved the logic for the placeholder to getPayloadForImageLoader(...)

this may still be not the best solution because the logic inside is also responsible for other things. 
but i think it's better than to call the super method in between other code which is now avoided.
see commit 4ccf8ac5a28e13a3a9f0095b7e0711251e876a4c
cc @AlvaroBrey

**Review by nickvergessen — APPROVED** [review]
🐘  Fixes the issue
