### PR TITLE
hopefully fix NPE for currentUser in addToConversationItems

### LINKED ISSUE #4610: NPE for currentUser in ConversationsListActivity
```
Exception java.lang.NullPointerException:
  at com.nextcloud.talk.conversationlist.ConversationsListActivity.addToConversationItems (ConversationsListActivity.kt:851)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity.access$addToConversationItems (ConversationsListActivity.kt:151)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invokeSuspend (ConversationsListActivity.kt:394)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invoke (Unknown Source:8)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invoke (Unknown Source:4)
```

v20.1.0

### PR DESCRIPTION
**Pull request by mahibi**
fix #4610

It seems there could have been a race condition because currentUser was initialized too late.
 I was not able to reproduce but hopefully this fixes it:
 - initialize currentUser earlier (moved from onResume to onCreate)
 - use currentUserProvider instead userManager

NPEs were reported via gplay:

1)
```
Exception java.lang.NullPointerException:
  at com.nextcloud.talk.conversationlist.ConversationsListActivity.addToConversationItems (ConversationsListActivity.kt:851)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity.access$addToConversationItems (ConversationsListActivity.kt:151)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invokeSuspend (ConversationsListActivity.kt:394)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invoke (Unknown Source:8)
  at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invoke (Unknown Source:4)
```

2)
```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:5427)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5508)
  ...
Caused by java.lang.NullPointerException:
  at com.nextcloud.talk.conversationlist.ConversationsListActivity.shouldShowNotificationWarning (ConversationsListActivity.kt:1557)
```

---

Long term solution: https://github.com/nextcloud/talk-android/issues/4609 + better usage of MVVM

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt [hunk 1]
```diff
@@ -235,6 +235,8 @@ class ConversationsListActivity :
         super.onCreate(savedInstanceState)
         NextcloudTalkApplication.sharedApplication!!.componentApplication.inject(this)
 
+        currentUser = currentUserProvider.currentUser.blockingGet()
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt:238]: Rather than blocking the thread, you can observe the result on main thread.

`private var currentUserDisposable: Disposable? = null`


```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        NextcloudTalkApplication.sharedApplication!!.componentApplication.inject(this)

        currentUserDisposable = currentUserProvider.currentUser
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe { user ->
                currentUser = user

                conversationsListViewModel = ViewModelProvider(this, viewModelFactory)[ConversationsListViewModel::class.java]

                binding = ActivityConversationsBinding.inflate(layoutInflater)
                setupActionBar()
                setContentView(binding.root)
                setupSystemColors()
                viewThemeUtils.material.themeCardView(binding.searchToolbar)
                viewThemeUtils.material.themeSearchBarText(binding.searchText)

                forwardMessage = intent.getBooleanExtra(KEY_FORWARD_MSG_FLAG, false)
                onBackPressedDispatcher.addCallback(this, onBackPressedCallback)

                initObservers()
            }
    }
```

```
public override fun onDestroy() {
        super.onDestroy()
        dispose(null)
        if (searchViewDisposable != null && !searchViewDisposable!!.isDisposed) {
            searchViewDisposable!!.dispose()
        }

        currentUserDisposable?.dispose()
    }
```

**Review by alperozturk96 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt (hunk 1 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt:238]: The 
[CurrentUserProviderImpl](https://github.com/nextcloud/talk-android/blob/f5a4274e545f506861dc7baf7f92ec5e73d674f6/app/src/main/java/com/nextcloud/talk/utils/database/user/CurrentUserProviderImpl.kt)
was implemented so that retrieving the user via

`currentUserProvider.currentUser.blockingGet()`

is reasonable.

Given the amount of how many times the user is queried in code, adding observers and disposables in all places would cause so much boilerplate.

I agree that it should be replaced with more modern coroutine handling, but until then i think usage of 
currentUserProvider.currentUser.blockingGet()
is okay.

Does this make sense or is this a no go for you @alperozturk96 ?

Comment (alperozturk96) [reply app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt:238]: [blockingGet()](https://reactivex.io/RxJava/2.x/javadoc/2.0.8/io/reactivex/Maybe.html#blockingGet()) does not use any particular Schedulers. It means it can run on MainThread and **may** cause an issue.

Ideally, CurrentUserProviderImpl should handle this and do the necessary jobs. You don't have to repeat for every class.

This is how you should handle RxJava code. I just wanted to share.

But since this PR focuses on the NPE fix, we can move forward.

**Review by alperozturk96 — APPROVED** [review]

File: app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt (hunk 1 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt:238]: Thanks to clarify, we can have a closer look together maybe when replacing the CurrentUserProviderImpl...
