### PR TITLE
fix displaying of large images

### LINKED ISSUE #1190: Not displaying images
## Steps to reproduce

1. Receive the image in the conversation.
2. Tap on an image to view it in full size.

The image is not displayed. Only a black background with three dots appears (kebab menu).

I also noticed that after tapping on the image there is no reaction for a long time. This confuses the user. Doesn't know if the application worked properly. In my opinion, there should be a loading wheel or other information about the image loading.

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 08

### PR DESCRIPTION
**Pull request by mahibi**
fix #1190 

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### CODE REVIEW

**Comment by nickvergessen** [comment]
Couldn't reproduce an issue before, but code is in the files app, so should be fine.

Tested with https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73751/world.topo.bathy.200407.3x5400x2700.jpg

File: app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+                0,
+                0,
+                bitmap.getWidth(),
+                bitmap.getHeight(),
+                matrix,
+                true
+            )
+            return rotatedBitmap
+        } catch (e: IOException) {
+            Log.e(TAG, "error while rotating image")
```
Comment (AndyScherzinger) [inline app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt:115]: I'd add the exception as a 3rd parameter

Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt:115]: > Couldn't reproduce an issue before, but code is in the files app, so should be fine.

infact i went for an other solution: https://developer.android.com/topic/performance/graphics/load-bitmap

File: app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+import android.graphics.Bitmap
+import android.graphics.BitmapFactory
+import android.graphics.Matrix
+import android.media.ExifInterface
+import android.util.Log
+import java.io.IOException
+
+/**
+ * https://developer.android.com/topic/performance/graphics/load-bitmap.
+ * https://stackoverflow.com/a/15341203
```
Comment (AndyScherzinger) [inline app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt:32]: Stack overflow uses https://stackoverflow.com/help/licensing while I don't know if this leads to any issues in combination with GPLv3+ and also I don't know which license android.com uses. So I guess it can't be re-licensed as GPLv3  (both sources) and I don't know if GPLv3 and CC-BY can code exist.

Looping in @schiessle for some licensing feedback ❤️

**Comment by mahibi** [comment]
> Couldn't reproduce an issue before, but code is in the files app, so should be fine.

infact i went for an other solution: https://developer.android.com/topic/performance/graphics/load-bitmap

File: app/build.gradle [hunk 3]
```diff
@@ -186,6 +186,7 @@ dependencies {
     implementation "androidx.work:work-runtime:${workVersion}"
     implementation "androidx.work:work-rxjava2:${workVersion}"
     implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
+    implementation 'androidx.exifinterface:exifinterface:1.3.0-rc01'
```
Comment (AndyScherzinger) [inline app/build.gradle:189]: @mahibi Any reason for using ```1.3.0-rc01```? I'd advice to use latest which according to https://developer.android.com/jetpack/androidx/releases/exifinterface is ```1.3.2```

**Review by AndyScherzinger — APPROVED** [review]
Looks good just one minor comment regarding the lib-version

**Comment by AndyScherzinger** [comment]
@mahibi and dete3kt isn't happy... -> https://github.com/nextcloud/talk-android/pull/1283/checks?check_run_id=2782243685

File: app/build.gradle (hunk 3 above)
Comment (mahibi) [reply app/build.gradle]: ah thx. came in via auto suggestion

**Comment by mahibi** [comment]
> @mahibi and detekt isn't happy... -> https://github.com/nextcloud/talk-android/pull/1283/checks?check_run_id=2782243685

fixed the detect issues for the 2 files of this PR
