### PR TITLE
group chat messages

### LINKED ISSUE #1747: Messages grouped wrong
Messages are grouped wrong in 1-to-1 and group conversations:

| Android | Spreed |
| :-: | :-: |
| image | image |

### PR DESCRIPTION
**Pull request by sowjanyakch**
fix #1747

Align with web on grouping messages.

- [x] Group messages from same author sent on the same day and time difference should be less than or equal to 5 minutes.
- [x] Never group bot messages (apart from changelog bot)
- [x] Also group system messages from different users
- [x] Never group edited messages.

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 1]
```diff
@@ -2600,11 +2600,10 @@ class ChatActivity :
             chatMessage.activeUser = conversationUser
 
             adapter?.let {
-                chatMessage.isGrouped = (
-                    it.isPreviousSameAuthor(chatMessage.actorId, -1) &&
-                        it.getSameAuthorLastMessagesCount(chatMessage.actorId) %
-                        GROUPED_MESSAGES_SAME_AUTHOR_THRESHOLD > 0
-                    )
+                val lastItemIndex = adapter!!.itemCount - 1
+                val previousChatMessage = adapter!!.items[lastItemIndex].item as ChatMessage
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:2604]: `previousChatMessage` is not calculated correctly.

When querying
`adapter!!.itemCount - 1`

you would get some old messages (the oldest one available in the adapter).

The newest message has index 0

So it's just
`val previousChatMessage = adapter!!.items[0].item as ChatMessage`

But also it must be checked if the message is a ChatMessage. Otherwise there will be cast exceptions, for example when it's a date-message (the ones that are shown between the messages, saying "Today", "Yesterday", ...). Just look into the implementation of `isPreviousSameAuthor` to see the checks that may be necessary.

**Review by mahibi — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 2]
```diff
@@ -2600,11 +2600,9 @@ class ChatActivity :
             chatMessage.activeUser = conversationUser
 
             adapter?.let {
-                chatMessage.isGrouped = (
-                    it.isPreviousSameAuthor(chatMessage.actorId, -1) &&
-                        it.getSameAuthorLastMessagesCount(chatMessage.actorId) %
-                        GROUPED_MESSAGES_SAME_AUTHOR_THRESHOLD > 0
-                    )
+                val previousChatMessage = adapter!!.items[1].item as ChatMessage
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:2603]: As said, there must be checks if the previousChatMessage is a ChatMessage.
To reproduce this crashes when the check is not in place, write a message from webuser to androiduser in a chat that does not yet have any message for this day.

**Review by mahibi — CHANGES_REQUESTED** [review]

**Comment by mahibi** [comment]
when testing i got
grafik

while for server it is
grafik

This happened when i sent messages while being in the chat, so must be caused in `processMessagesFromTheFuture`

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 3]
```diff
@@ -2688,6 +2677,40 @@ class ChatActivity :
...
+                )
+        ) {
+            return false
+        }
+
+        val timeDifference = dateUtils.getTimeDifferenceInSeconds(
+            message2.timestamp,
+            message1.timestamp
+        )
+        val isLessThan5Min = timeDifference > 300
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:2703]: 300 should be a const val FIVE_MINUTES_IN_SECONDS

**Comment by sowjanyakch** [comment]
> when testing i got 
grafik
> 

@mahibi - Does this happens for you all the times or sometimes?

**Review by mahibi — APPROVED** [review]

**Comment by mahibi** [comment]
> > when testing i got
> > grafik
> 
> @mahibi - Does this happens to you all the times or only sometimes?

tested again and cant reproduce. For me it's fine to merge then
