### PR TITLE
Unable to change user status during a call 

### LINKED ISSUE #4478: Unable to change user status during a call
### Steps to reproduce

1. Clear the Status Message.
2. Start a call.
3. The status is automatically set to "In a call" when you are in call.
4. Try to change the status.

### Expected behaviour

User should be able to change the status.

### Actual behaviour

User cannot change the status. Status dialog is collapsed.

### Device brand and model

Samsung A52

### Android version

11

### Nextcloud Talk app version

20.1.0 Alpha 15

### Nextcloud server version

_No response_

### Talk version

v20.1.0 Alpha 15

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

### Android logs

_No response_

### Server log

```bash

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sowjanyakch**
Resolve #4478 

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt [hunk 1]
```diff
@@ -177,17 +177,19 @@ class SetStatusDialogFragment :
                 override fun onNext(statusOverall: StatusOverall) {
                     if (statusOverall.ocs?.meta?.statusCode == HTTP_STATUS_CODE_OK) {
                         backupStatus = statusOverall.ocs?.data!!
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt:179]: better use

statusOverall.ocs?.data?.let{
..... it.
}

in case data is null somehow

**Review by mahibi — CHANGES_REQUESTED** [review]

**Review by mahibi — APPROVED** [review]
