### PR TITLE
fix missing deck card links / always show links if available in message

### LINKED ISSUE #1025: deck card link is show as {object}
Browser:
image

App:
image

### PR DESCRIPTION
**Pull request by mahibi**
fix #1025 
Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+package com.nextcloud.talk.models.json.chat
+
+import java.util.*
+
+class ChatUtils {
+    companion object {
+        fun getParsedMessage(message: String?, messageParameters: HashMap<String?, HashMap<String?, String?>>?):
+                String? {
+            var message = message
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:31]: That's uncommon, or?
If you want to you can change parameter to "var message" directly.

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+            if (messageParameters != null && messageParameters.size > 0) {
+                for (key in messageParameters.keys) {
+                    val individualHashMap = messageParameters[key]
+                    val type = individualHashMap?.get("type")
+                    if (type == "user" || type == "guest" || type == "call") {
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:36]: type can be null if individualHashMap is null.
When you use "user" == type then it will not crash with NPE.

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package com.nextcloud.talk.models.json.chat
+
+import java.util.*
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:25]: try to avoid this generic imports

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+        fun getParsedMessage(message: String?, messageParameters: HashMap<String?, HashMap<String?, String?>>?):
+                String? {
+            var message = message
+            if (messageParameters != null && messageParameters.size > 0) {
+                for (key in messageParameters.keys) {
+                    val individualHashMap = messageParameters[key]
+                    val type = individualHashMap?.get("type")
+                    if (type == "user" || type == "guest" || type == "call") {
+                        message = message?.replace("{$key}", "@" + individualHashMap["name"])
+                    } else if (individualHashMap?.containsKey("link") == true) {
```
Comment (tobiasKaminsky) [inline app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:38]: == true is unnecessary.

Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:38]: grafik

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt (hunk 3 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:25]: agree.
in fact is was even not needed

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt (hunk 1 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:31]: for function parameters "var" is not allowed in kotlin (https://discuss.kotlinlang.org/t/method-parameters-and-mutable-variables/333). I guess you were thinking about primary constructors for classes where it is allowed.

`var message = message`  is called "shadowing" (https://stackoverflow.com/questions/49680040/why-kotlin-allows-to-declare-variable-with-the-same-name-as-parameter-inside-the), but maybe it's not best practice here.
so i will go for
`var resultMessage = message`
Not sure if this is best practice so i'm open to other ideas..

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt (hunk 2 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:36]: this will not throw a NPE. 
This would resolve to  `null == "user"` which is "false"
I guess you were thinking about java where it's better to check for
`"mystring".equals(value)`
in case of
`value.equals("mysting")` (-> NPE if value is null)
?

Comment (tobiasKaminsky) [reply app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:34]: Right, bad Java habits ;-)

File: app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt (hunk 4 above)
Comment (tobiasKaminsky) [reply app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt:36]: True 🤣
I overlooked "?."

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by jakobroehrl** [comment]
@mahibi @stefan-niedermann 
Is it possible to open the card in the Android App if installed?

**Comment by stefan-niedermann** [comment]
@jakobroehrl yes, there are two options:

1. talk directly checks whether deck is installed and launches an intent
2. Deck catches the browser-open action and opens itself (https://github.com/stefan-niedermann/nextcloud-deck/issues/498)
