### PR TITLE
avoid crashes with NPEs for bindings

### LINKED ISSUE #2666: Crashes because of NPE in ControllerViewBindingDelegate
### Steps to reproduce

can happen randomly

### Expected behaviour

no crash

### Actual behaviour

see NPE's in gplay console.

examples:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nextcloud.talk2, PID: 5251
    java.lang.NullPointerException
        at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue(ControllerViewBindingDelegate.kt:47)
        at com.nextcloud.talk.controllers.AccountVerificationController.getBinding(AccountVerificationController.kt:83)
        at com.nextcloud.talk.controllers.AccountVerificationController.onMessageEvent$lambda$0(AccountVerificationController.kt:383)
        at com.nextcloud.talk.controllers.AccountVerificationController.$r8$lambda$IrbsuB1hlVctlTGw6Cl6z1cfNI4(Unknown Source:0)
        at com.nextcloud.talk.controllers.AccountVerificationController$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/okhttp.OkHttpClient: <-- 200 OK https://push-notifications.nextcloud.com/devices (77ms)
I/okhttp.OkHttpClient: Server: nginx
I/okhttp.OkHttpClient: Date: Wed, 04 Jan 2023 13:57:29 GMT
I/okhttp.OkHttpClient: Content-Type: text/plain; charset=utf-8
I/okhttp.OkHttpClient: Content-Length: 1
I/okhttp.OkHttpClient: Connection: keep-alive
I/okhttp.OkHttpClient: X-Content-Type-Options: nosniff
I/okhttp.OkHttpClient: Strict-Transport-Security: max-age=15768000
I/okhttp.OkHttpClient: 
I/okhttp.OkHttpClient: <-- END HTTP (1-byte body)
```

startAudioRecording:

```

Exception java.lang.NullPointerException:
  at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue (ControllerViewBindingDelegate.kt:47)
  at com.nextcloud.talk.controllers.ChatController.getBinding (ChatController.kt:230)
  at com.nextcloud.talk.controllers.ChatController.startAudioRecording (ChatController.kt:1160)
  at com.nextcloud.talk.controllers.ChatController.access$startAudioRecording (ChatController.kt:216)
  at com.nextcloud.talk.controllers.ChatController$onViewBound$10.onTouch (ChatController.kt:800)
  at android.view.View.dispatchTouchEvent (View.java:15072)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3923)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:3538)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3923)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:3538)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3923)
```

showUserProfile:
```
Exception java.lang.NullPointerException:
  at com.nextcloud.talk.controllers.util.ControllerViewBindingDelegate.getValue (ControllerViewBindingDelegate.kt:47)
  at com.nextcloud.talk.controllers.ProfileController.getBinding (ProfileController.kt:99)
  at com.nextcloud.talk.controllers.ProfileController.showUserProfile (ProfileController.kt:286)
  at com.nextcloud.talk.controllers.ProfileController.access$showUserProfile (ProfileController.kt:96)
  at com.nextcloud.talk.controllers.ProfileController$onAttach$5.onNext (ProfileController.kt:245)
  at com.nextcloud.talk.controllers.ProfileController$onAttach$5.onNext (ProfileController.kt:238)
```

### PR DESCRIPTION
**Pull request by mahibi**
fix #2666

- [ ] todo: remove NPE checks commented with "view binding can be null"

### 🏁 Checklist

- [x] ⛑️ Tests (unit and/or integration) are included or not needed
- [x] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [x] 📅 Milestone is set
- [x] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt [hunk 1]
```diff
@@ -25,13 +25,13 @@ import com.bluelinelabs.conductor.Controller
...
-fun <T : ViewBinding> Controller.viewBinding(bindingFactory: (View) -> T) =
+fun <T : ViewBinding> Controller.viewBinding(bindingFactory: (View) -> T?) =
     ControllerViewBindingDelegate(this, bindingFactory)
 
 class ControllerViewBindingDelegate<T : ViewBinding>(
     controller: Controller,
-    private val viewBinder: (View) -> T
-) : ReadOnlyProperty<Controller, T>, LifecycleObserver {
+    private val viewBinder: (View) -> T?
+) : ReadOnlyProperty<Controller, T?>, LifecycleObserver {
```
Comment (AlvaroBrey) [inline app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt:34]: I think you can keep `bindingFactory` and `viewBinder` as returning `T` (not nullable). The only place it needs to be nullable is on the `getValue` and the `ReadOnlyProperty` definition.

File: app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt [hunk 2]
```diff
@@ -43,7 +43,7 @@ class ControllerViewBindingDelegate<T : ViewBinding>(
         })
     }
 
-    override fun getValue(thisRef: Controller, property: KProperty<*>): T {
-        return binding ?: viewBinder(thisRef.view!!).also { binding = it }
+    override fun getValue(thisRef: Controller, property: KProperty <*>): T? {
+        return binding ?: thisRef.view?.let { viewBinder(it).also { binding = it } }
```
Comment (AlvaroBrey) [inline app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt:47]: This looks a bit too complicated to still be a `?:`. I'd change this into a proper if-else for readability.

File: app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt [hunk 3]
```diff
@@ -496,35 +496,35 @@ class OperationsMenuController(args: Bundle) : BaseController(
                     )
                 }
             }
-            binding.resultImageView.visibility = View.VISIBLE
+            binding?.resultImageView?.visibility = View.VISIBLE
```
Comment (AlvaroBrey) [inline app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt:499]: In places like this it makes more sense to do `binding?.let{...}` and then you have a non-null reference inside, instead of repeating the null checks. But I understand this PR is just about getting it to work without NPEs first.

**Review by AlvaroBrey — APPROVED** [review]

File: app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt (hunk 2 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt]: you mean like in the last commit b37bd59ddc3a2d698180fcc2535a2531585b5199 ?

File: app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt [hunk 4]
```diff
@@ -43,7 +43,12 @@ class ControllerViewBindingDelegate<T : ViewBinding>(
...
 
-    override fun getValue(thisRef: Controller, property: KProperty<*>): T {
-        return binding ?: viewBinder(thisRef.view!!).also { binding = it }
+    override fun getValue(thisRef: Controller, property: KProperty<*>): T? {
+        return if (binding != null) {
+            binding
+        } else {
+            binding = thisRef.view?.let { viewBinder(it) }
+            binding
+        }
```
Comment (AlvaroBrey) [inline app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt:52]:
```suggestion
        if (binding == null) {
            binding = thisRef.view?.let { viewBinder(it) }
        }
        return binding
```

File: app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt (hunk 2 above)
Comment (AlvaroBrey) [reply app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt]: simpler still, see comment below
