### PR TITLE
fix TooManyRequestsException

### LINKED ISSUE #4503: ConnectivityManager$TooManyRequestsException
v20.0.6

```
Exception android.net.ConnectivityManager$TooManyRequestsException:
  at android.net.ConnectivityManager.convertServiceException (ConnectivityManager.java:3771)
  at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:3960)
  at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:3967)
  at android.net.ConnectivityManager.registerNetworkCallback (ConnectivityManager.java:4349)
  at android.net.ConnectivityManager.registerNetworkCallback (ConnectivityManager.java:4319)
  at com.nextcloud.talk.data.network.NetworkMonitorImpl$isOnline$1.invokeSuspend (NetworkMonitorImpl.kt:61)
  at com.nextcloud.talk.data.network.NetworkMonitorImpl$isOnline$1.invoke (Unknown Source:8)
  at com.nextcloud.talk.data.network.NetworkMonitorImpl$isOnline$1.invoke (Unknown Source:4)
  at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl (Builders.kt:316)
  at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo (Unknown Source)
  at kotlinx.coroutines.flow.CallbackFlowBuilder.collectTo (Builders.kt:330)
  at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend (ChannelFlow.kt:56)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:104)
  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run (LimitedDispatcher.kt:111)
  at kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:99)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:584)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:811)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:715)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:702)
```

### PR DESCRIPTION
**Pull request by mahibi**
fix #4503

By using
`networkMonitor.isOnline.first()`
the function
`unregisterNetworkCallback`
was triggered, which sometimes caused the ConnectivityManager$TooManyRequestsException.

So each time isOnline.first() was called, the callbackFlow would:
- Register a new NetworkCallback.
- Emit a value and cancel the flow.
- Unregister the NetworkCallback.

The exception was:
```
Exception android.net.ConnectivityManager$TooManyRequestsException:
  at android.net.ConnectivityManager.convertServiceException (ConnectivityManager.java:3771)
  at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:3960)
  at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:3967)
  at android.net.ConnectivityManager.registerNetworkCallback (ConnectivityManager.java:4349)
  at android.net.ConnectivityManager.registerNetworkCallback (ConnectivityManager.java:4319)
  at com.nextcloud.talk.data.network.NetworkMonitorImpl$isOnline$1.invokeSuspend (NetworkMonitorImpl.kt:61)
```

To fix this, the cold flow from callbackFlow is converted to a StateFlow.

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt [hunk 1]
```diff
@@ -134,7 +134,7 @@ class OutcomingTextMessageViewHolder(itemView: View) :
         }
 
         CoroutineScope(Dispatchers.Main).launch {
-            if (message.isTemporary && !networkMonitor.isOnline.first()) {
+            if (message.isTemporary && !networkMonitor.isOnline.value) {
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt:137]: .value not will give most updated version. You can use collectLatest. Also since ViewHolder doesn't have lifeCycleScope you should manually cancel the job.

```
 private val job = Job()
 private val scope = CoroutineScope(Dispatchers.Main + job)
```

```
scope.launch {
            networkMonitor.isOnline.collectLatest { isOnline ->
                if (message.isTemporary && !isOnline) {
                    updateStatus(
                        R.drawable.ic_signal_wifi_off_white_24dp,
                        context.resources?.getString(R.string.nc_message_offline)
                    )
                }
            }
        }
```

```
fun clear() {
        job.cancel()
    }
```

Don't forget to call clear from TalkMessagesListAdapter.

```
@Override
    public void onViewRecycled(ViewHolder holder) {
        super.onViewRecycled(holder);
        if (holder instanceof OutcomingTextMessageViewHolder holderInstance) {
            holderInstance.clear();
        }
   }
```

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 2]
```diff
@@ -452,7 +451,7 @@ class ChatActivity :
 
         this.lifecycleScope.launch {
             delay(DELAY_TO_SHOW_PROGRESS_BAR)
-            if (adapter?.isEmpty == true && networkMonitor.isOnline.first()) {
+            if (adapter?.isEmpty == true && networkMonitor.isOnline.value) {
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:454]: You should use collectLatest

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 3]
```diff
@@ -927,7 +926,7 @@ class ChatActivity :
             chatViewModel.getGeneralUIFlow.onEach { key ->
                 when (key) {
                     NO_OFFLINE_MESSAGES_FOUND -> {
-                        if (networkMonitor.isOnline.first().not()) {
+                        if (networkMonitor.isOnline.value.not()) {
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:929]: You should use collectLatest

File: app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt [hunk 4]
```diff
@@ -1357,7 +1356,7 @@ class ConversationsListActivity :
 
     override fun onItemLongClick(position: Int) {
         this.lifecycleScope.launch {
-            if (showShareToScreen || !networkMonitor.isOnline.first()) {
+            if (showShareToScreen || !networkMonitor.isOnline.value) {
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt:1359]: You should use collectLatest

File: app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt [hunk 5]
```diff
@@ -58,7 +58,7 @@ class OfflineFirstConversationsRepository @Inject constructor(
             val initialConversationModels = getListOfConversations(user.id!!)
             _roomListFlow.emit(initialConversationModels)
 
-            if (monitor.isOnline.first()) {
+            if (networkMonitor.isOnline.value) {
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt:61]: You should use collectLatest

File: app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt [hunk 6]
```diff
@@ -134,7 +133,7 @@ class MessageActionsDialog(
                         initMenuAddToNote(
                             !message.isDeleted &&
                                 !ConversationUtils.isNoteToSelfConversation(currentConversation) &&
-                                networkMonitor.isOnline.first(),
+                                networkMonitor.isOnline.value,
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt:136]: You should use collectLatest

File: app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt [hunk 7]
```diff
@@ -59,10 +58,9 @@ class TempMessageActionsDialog(
 
     private fun initMenuItems() {
         this.lifecycleScope.launch {
-            val isOnline = networkMonitor.isOnline.first()
-            initResendMessage(message.sendingFailed && isOnline)
-            initMenuEditMessage(message.sendingFailed || !isOnline)
-            initMenuDeleteMessage(message.sendingFailed || !isOnline)
+            initResendMessage(message.sendingFailed && networkMonitor.isOnline.value)
```
Comment (alperozturk96) [inline app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt:61]: You should use collectLatest

**Review by alperozturk96 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt (hunk 1 above)
Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt:137]: > ViewHolder doesn't have lifeCycleScope you should manually cancel the job

indeed, thanks

> .value not will give most updated version. You can use collectLatest.

I don't think so. Whenever the flow in NetworkMonitorImpl emits a new value via the callbackFlow, the value property is automatically updated. This is guaranteed to be the latest value so it is fine to use `networkMonitor.isOnline.value`

Comment (alperozturk96) [reply app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt:140]: Oh, I saw the callbackFlow implementation in that case yes it's returning the latest value and I also tested.

`val chatActivity = commonMessageInterface as ChatActivity` if this cast will always succeed, yes you can access the lifecycle scope of the ChatActivity and no need to use CoroutineScope.

**Review by alperozturk96 — APPROVED** [review]
