### PR TITLE
Bugfix/2446/fix disappearing accounts

### LINKED ISSUE #2446: Accounts disappear (+notifications are still delivered)
### Steps to reproduce

see below

### Expected behaviour

see both servers

### Actual behaviour

After updating from RC2 one of my two servers is gone, the account is away but I get notifications for this account. Reinstalling and adding my 2 servers does not solve it

### Device brand and model

Pixel 4a

### Android version

12

### Nextcloud Talk app version

15.0.0-rc.1

### Nextcloud server version

_No response_

### Talk version

_No response_

### Custom Signaling server configured

_No response_

### Custom TURN server configured

_No response_

### Custom STUN server configured

_No response_

### Android logs

_No response_

### Server log

_No response_

### Additional information

_No response_

### LINKED ISSUE #2531: App keeps crashed on startup
### Steps to reproduce

Opened the app app keeps crashing

### Expected behaviour

Should not crash. This happen a few days ago and i cleared the cache and data off the app and it started to work again. 

I collacted some adb phone logs ping me via IM so i can send them to you. 

### Actual behaviour

https://user-images.githubusercontent.com/59488153/198362491-04d5a673-b29d-4eb3-b1e8-57959ea59261.mp4

### Device brand and model

SM-G996U1 

### Android version

12

### Nextcloud Talk app version

15.0.1

### Nextcloud server version

24.0.6

### Talk version

14.0.5

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Android logs

_No response_

### Server log

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mahibi**
fix #2446
fix #2531

# Problem
There was a race condition for "updateUser" between 

`userManager.saveUser(user).subscribe(new SingleObserver<Integer>() {`
in PushUtils#updatePushStateForUser

and

`if (userManager.setUserAsActive(user).blockingGet()) {`
in ChooseAccountDialogFragment > onSwitchItemClickListener

So while switching accounts via the Account switcher, also the PushUtil method is executed and sometimes asynchronously overwrote other user attributes with old values:

## Scenario1: no users are marked as "current" -> could lead to **app crash on startup**
As a result of this, there could be no users marked as "current". 
Because of this, 

```
@Query("SELECT * FROM User where current = 1")
abstract fun getActiveUser(): Maybe<UserEntity>
```

would return null, which in turn led to a NullPointerException in ConversationsListController for currentUser and the app crashed.
Because it's not a valid state to have no users marked as current, the app always crashed on startup until the app data was deleted, see issue https://github.com/nextcloud/talk-android/issues/2531

remarks: it cannot be 100% ruled out that there are other async scenarios that lead to this state. Anyway the NPE is now avoided so that the app does not crash but shows an error in UI.

## Scenario2: multiple users are marked as "current" -> **accounts are suddenly hidden**
There could be more than one user marked with "current". This caused to only show one of the current accounts in the account switcher while the other one was hidden. So it seemed that an account was lost (although it was still there, that's why push notifications still could have been received), see issue https://github.com/nextcloud/talk-android/issues/2446

# Solution
update only pushState when updating users (instead updating of whole user)
see commit https://github.com/nextcloud/talk-android/pull/2581/commits/b8e3ce457e882fb0fe4d4de02178c316ea025bf5

# How to test
set up multiple accounts and switch very fast and often between them via the account switch dialog (the avatar in the upper right corner)

## without this PR
sometimes scenario 1 or 2 could happen.

## with this PR
neither scenario 1 or 2 occur

### CODE REVIEW

**Comment by mahibi** [comment]
As a discussion:

i came to the solution because i saw that 
`cookieManager.cookieStore.removeAll()`
is used in combination with `setUserAsActive()` also in other classes, for example here:
https://github.com/nextcloud/talk-android/blob/master/app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt#L91

But i would not be able to tell what exactly `cookieManager.cookieStore.removeAll()` does. Can you, @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
@mahibi the call throws away all Cookie data. This is needed since else when switching to a user of the same URL then the http client would send the cookie data of the former user which is wrong and leads to issues with loading the wrong data on server side, hence the deletion of cookie data upon user switch.

**Comment by mahibi** [comment]
> @mahibi the call throws away all Cookie data. This is needed since else when switching to a user of the same URL then the http client would send the cookie data of the former user which is wrong and leads to issues with loading the wrong data on server side, hence the deletion of cookie data upon user switch.

are you sure this only applies to users with the same URL?
in my scenario it was sermo, cnc and some complete different url.
other users for this issue reported they used 2 servers with different urls...

**Comment by mahibi** [comment]
there must 2 different bugs!
- sometimes there is no new user created when trying to add him
- sometimes the user is added but other accounts remain "current"

**Comment by mahibi** [comment]
added some debug logging.
i can't reproduce it now but didn't change anything. it's really hard to reproduce & debug! might be some async problem..

**Comment by migulen** [comment]
Hi @mahibi, 

I'm testing this nextcoud-talk QA fix with 2 accounts in 2 different servers. It's the same scenario: "same servers, same mobile terminal and same mobile company and wifi networks" that I related in the original post/bug "2446", but these are testing accounts with different username).  By now, only 12 hours of use, I haven't any "disappearing account" with this bugfix... but it used only a bit.

On the same mobile terminal, the original scenario (real accounts) is configured with v15.0.1 nextcloud-talk at the same time. Today in the 12 hours of use, 2 o 3 times the reals account have disappeared, alternatively. 

I'll continue reporting.

**Comment by migulen** [comment]
By the way, I've found that in the testing scenario (QA) I have this bug (https://github.com/nextcloud/talk-android/issues/2587 too), **but only happening on one of the new testing accounts ¿?¿?¿?** 

How it's possible ? It's the same app and I think that i've created the testing accounts on the 2 servers exactly with the same protocol... and configured at the app the same way.

:-(

**Comment by migulen** [comment]
Hi @mahibi , I don't use so much the "test accounts" and for now, these haven't disappeared any time. May I reinstall 2581-talk.apk and continue testing ? Or 2581-talk.apk it's the same that I installed some days ago ?

"i was able to see that the loop was somehow interrupted during debugging which caused two users to have **current =true**" <- That's just what I thought.

**Comment by mahibi** [comment]
if anyone is interested to test, please fell free to do so 
@migulen 
@jakobroehrl

File: app/src/main/java/com/nextcloud/talk/users/UserManager.kt [hunk 1]
```diff
@@ -43,6 +43,7 @@ class UserManager internal constructor(private val userRepository: UsersReposito
     val currentUser: Maybe<User>
         get() {
             return userRepository.getActiveUser()
+                .switchIfEmpty(getAnyUserAndSetAsActive())
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/users/UserManager.kt:46]: this should fix the app on phones that have an invalid state because of no users marked as "current".
:+1: or :-1: @AlvaroBrey ?

Comment (AlvaroBrey) [reply app/src/main/java/com/nextcloud/talk/users/UserManager.kt:46]: Yeah, I don't see any problem with this.

However I will say that most classes should aim to use `CurrentUserProvider` instead,  which always holds a reference to the updated current user, without having to call the DB every time.

Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/users/UserManager.kt:46]: :+1: but for now PR approved?

Comment (AlvaroBrey) [reply app/src/main/java/com/nextcloud/talk/users/UserManager.kt:46]: I don't have the bandwidth to review the full PR right now, but as I said, no problem with this.

**Review by timkrueger — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]
