### PR TITLE
Bugfix/4883/fix jumping note to self entry

### LINKED ISSUE #4883: Message long press menu is "jumping"
1. Long press on a message being ready to copy it
2. Try to click the action but the menu jumps as a single entry is rendered later?

I think it's the "note to self" that takes some time?

Especially annoying, when you then switch to another conversation and long press on another message it seems to check it again and flickers again.
The fact that this option exists should be independent from any other information, so why is it "jumping in" later?

### PR DESCRIPTION
**Pull request by mahibi**
fix #4883

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 1]
```diff
@@ -3295,37 +3295,61 @@ class ChatActivity :
...
+            intArrayOf(ApiUtils.API_V4, ApiUtils.API_V3, 1)
+        )
+        chatViewModel.checkForNoteToSelf(
+            ApiUtils.getCredentials(conversationUser!!.username, conversationUser!!.token)!!,
+            ApiUtils.getUrlForRooms(
+                apiVersion,
+                conversationUser!!.baseUrl
+            ),
+            false
+        )
```
Comment (nickvergessen) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt:3310]: As long as this is only done when the action is pressed, instead of getting all rooms and searching for the note-to-self, can you GET the room with the token `note-to-self`? That will create it in case it was (accidentally) deleted

Comment (mahibi) [reply app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt]: improved with ab19f631aeb4264e894da4075ce524131f727723

**Review by sowjanyakch — APPROVED** [review]
