### PR TITLE
fix NPE in BitmapShrinker

### LINKED ISSUE #5600: NPE in BitmapShrinker
from gplay:

from 20.0.2 (and maybe older) up to 22.0.3

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4049)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4236)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:112)
  at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem (TransactionExecutor.java:174)
  at android.app.servertransaction.TransactionExecutor.executeTransactionItems (TransactionExecutor.java:109)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:81)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2637)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loopOnce (Looper.java:232)
  at android.os.Looper.loop (Looper.java:317)
  at android.app.ActivityThread.main (ActivityThread.java:8751)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:580)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:892)
Caused by java.lang.NullPointerException: run(...) must not be null
  at com.nextcloud.talk.utils.BitmapShrinker.decodeBitmap (BitmapShrinker.kt:31)
  at com.nextcloud.talk.utils.BitmapShrinker.shrinkBitmap (BitmapShrinker.kt:25)
  at com.nextcloud.talk.fullscreenfile.FullScreenImageActivity.displayImage (FullScreenImageActivity.kt:143)
  at com.nextcloud.talk.fullscreenfile.FullScreenImageActivity.onCreate (FullScreenImageActivity.kt:134)
  at android.app.Activity.performCreate (Activity.java:9002)
  at android.app.Activity.performCreate (Activity.java:8980)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1527)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:4031)
```

### PR DESCRIPTION
**Pull request by sowjanyakch**
fix #5600

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt [hunk 1]
```diff
@@ -21,19 +21,25 @@ object BitmapShrinker {
...
             inSampleSize = getInSampleSize(this, requestedWidth, requestedHeight)
             inJustDecodeBounds = false
-            BitmapFactory.decodeFile(path, this)
+            BitmapFactory.decodeFile(path, this)?.also { bitmap ->
+                Log.d(TAG, "Bitmap decoded successfully from path: $path")
+                return@run bitmap
+            }
+
+            Log.e(TAG, "Failed to decode bitmap from path: $path")
+            null
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt]: i think this is easier to read?::        

```
val decodedBitmap = BitmapFactory.decodeFile(path, this)
        
if (decodedBitmap == null) {
     Log.e(TAG, "Failed to decode bitmap from path: $path")
} 

decodedBitmap
```

File: app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt [hunk 2]
```diff
@@ -21,19 +21,25 @@ object BitmapShrinker {
...
-    fun shrinkBitmap(path: String, reqWidth: Int, reqHeight: Int): Bitmap {
-        val bitmap = decodeBitmap(path, reqWidth, reqHeight)
+    fun shrinkBitmap(path: String, reqWidth: Int, reqHeight: Int): Bitmap? {
+        val bitmap = decodeBitmap(path, reqWidth, reqHeight) ?: return null
         return rotateBitmap(path, bitmap)
     }
 
     // solution inspired by https://developer.android.com/topic/performance/graphics/load-bitmap
-    private fun decodeBitmap(path: String, requestedWidth: Int, requestedHeight: Int): Bitmap =
+    private fun decodeBitmap(path: String, requestedWidth: Int, requestedHeight: Int): Bitmap? =
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt:29]: Did you try out some things why it actually fails?
E.g. did you try with specials chars in path like in the other recent PR? So the same fix could be applied..

Comment (sowjanyakch) [reply app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt:29]: This will happen due to an invalid or corrupt file, or if the bitmap is too large(running out of memory during decoding). In all these cases, decodeFile() returns null instead of an exception.
