### PR TITLE
fix duplicate messages

### LINKED ISSUE #5068: Duplicate messages in missing microphone permissions scenario
STR:
1. Don't grant "Talk" Microphone permissions.
2. Create a new conversation and send text message.
3. Send a voice message, you will see duplicate messages.
4. Click on attachment icon and select "Take photo", now camera opens - try to navigate back, you will see duplicate messages.

duplicate messages occur when uploading messages from gallery, also sharing a contact without permissions

It's just UI, so nothing is duplicated persistently..

Seen on v21.1.0

### PR DESCRIPTION
**Pull request by sowjanyakch**
Resolve #5068

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt [hunk 1]
```diff
@@ -1334,7 +1334,9 @@ class ChatActivity :
 
         cancelNotificationsForCurrentConversation()
 
-        chatViewModel.getRoom(roomToken)
+        if (adapter == null) {
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt]: This feels like it might introduce a race condition..

In onCreate, initObservers() is called which in turn initializes the adapter in
```
            chatViewModel.getConversationFlow
                .onEach ....
```

At the same time, onResume is executed with the current check. This might be a race condition as we can not be sure if adapter is initialized or not. So getRoom may not be triggered when it should?

**Review by mahibi — CHANGES_REQUESTED** [review]

**Comment by sowjanyakch** [comment]
When the user opens the camera to take a picture or share a contact, the app goes into onPause(). The adapter is set to null.

When the user comes back to the app (onResume()), the messages are reloaded again preventing duplicate messages.

**Review by rapterjet2004 — APPROVED** [review]
