### PR TITLE
Team mentions

### LINKED ISSUE #4672: Circles / Teams support
## Bug: Adding / Removing system messages

Regression from the past as adding circles/teams was supported since a long time

Web | iOS | Android
---|---|---
Image | Image | Image

## Bug: Passive Team Mention support

Web | Android
---|---
Image | Image

## Bug: General placeholder support

The second part is especially sad, because it was discussed in the past, that all placeholders independent if they are "known" / "supported" should be replaced with the provided "name" field and if there is a "link" make it clickable towards that. E.g. this is how it looks in iOS before Implementing "mention bubbles for teams":

Image

---

- 🔥 Everything above **must** be fixed before 21.0.0
- 🐶 Everything below **should** be addressed, best before 21.0.0 otherwise quickly afterwards, latest 21.0.1

---

## Feature: Active Team Mention support

New feature introduced in 
- https://github.com/nextcloud/spreed/pull/14204
- https://github.com/nextcloud/spreed/pull/14242
- https://github.com/nextcloud/talk-ios/pull/1966

Show teams as mention suggestions and also make sure that editing messages with mentions works properly

### PR DESCRIPTION
**Pull request by sowjanyakch**
Resolve #4672

- [X] Show proper system messages when adding/ removing a team.
- [X] Implement team mention support.
- [ ] General placeholder support for mentions (will implement this in a different PR).

### 🖼️ Screenshots

Before | After
---|---
team_mentions_bug| team_mentions

### 🚧 TODO

- [ ] ...

### 🏁 Checklist

- [ ] ⛑️ Tests (unit and/or integration) are included or not needed
- [ ] 🔖 Capability is checked or not needed 
- [ ] 🔙 Backport requests are created or not needed: `/backport to stable-xx.x`
- [ ] 📅 Milestone is set
- [ ] 🌸 PR title is meaningful (if it should be in the changelog: is it meaningful to users?)

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt [hunk 1]
```diff
@@ -838,7 +838,8 @@ class MessageInputFragment : Fragment() {
                     mentionId.contains("@") ||
                     mentionId.startsWith("guest/") ||
```
Comment (nickvergessen) [inline app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt:839]:
```suggestion
                    mentionId.contains("/")
```

And simplify your life? ;)

**Review by mahibi — APPROVED** [review]
