### PR TITLE
avoid crash when clicking on header in conversation search mode

### LINKED ISSUE #1893: Clicking on "open conversation" crashes
## Steps to reproduce
1. search for a conversation that is open
2. click on "open conversation"
3. (sidenote: in german it is currently called "Unterhaltung öffnen", but it should be "Offene Unterhaltungen"

### Expected behaviour
No crash

### Actual behaviour
Crash 

## Device information

**Device:** Fairphone2/…

**Android version:** 10/…

**Talk version:** 11.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`)

**Talk version:** (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`)

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

### PR DESCRIPTION
**Pull request by mahibi**
fix #1893

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java [hunk 1]
```diff
@@ -857,17 +857,22 @@ protected String getTitle() {
...
+                    handleSharedData();
+                    showShareToScreen = false;
+                } else if (forwardMessage) {
+                    openConversation(bundle.getString(BundleKeys.INSTANCE.getKEY_FORWARD_MSG_TEXT()));
+                    forwardMessage = false;
+                } else {
+                    openConversation();
+                }
             }
+        } catch (ClassCastException e) {
```
Comment (mahibi) [inline app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java:873]: auto format kicked in so might be hard to find the fix..
this try catch is the only change for the fix....

**Review by AndyScherzinger — APPROVED** [review]
Successfully tested
