### PR TITLE
set locationName to "Shared location" when geocoding failed

### LINKED ISSUE #1393: Location name "null" not handled
## Steps to reproduce
1. Try to share a location
2. Pick the middle of the ocean
3. 

### Expected behaviour
Location is shared with label "Shared location" like in iOS

### Actual behaviour
Location is shared with label "null"

### PR DESCRIPTION
**Pull request by mahibi**
fix #1393 

Signed-off-by: Marcel Hibbe <dev@mhibbe.de>

### CODE REVIEW

File: app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt [hunk 1]
```diff
@@ -386,9 +386,15 @@ class LocationPickerController(args: Bundle) :
 
     private fun executeShareLocation(selectedLat: Double?, selectedLon: Double?, locationName: String?) {
         val objectId = "geo:$selectedLat,$selectedLon"
+
+        var locationNameToShare = locationName
+        if (locationNameToShare.isNullOrBlank()){
```
Comment (nickvergessen) [inline app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt:391]:
```suggestion
        if (locationNameToShare.isNullOrBlank()) {
```

**Review by nickvergessen — APPROVED** [review]

**Review by timkrueger — APPROVED** [review]
